name = "Lanyon"
license = "MIT"
licenselink = "https://github.com/tummychow/lanyon-hugo/blob/master/LICENSE.md"
description = "Lanyon-Hugo is a theme designed for blogging."
homepage = "https://github.com/thinkcache/"
tags = ["master","slave","master2"]
features = ["blog","master1" ]
min_version = 0.14
[author]
    name = "tummychow"

[original]
    author =  "mdo"
    homepage = "https://github.com/poole/lanyon"
    repo = "https://github.com/poole/lanyon"
